processcurrent: true
patterns:
  - client: system
    portrules:
      - name: capture_1
        target: "jack_mixer:System Capture L"
      - name: capture_2
        target: "jack_mixer:System Capture R"
  - client: jack_mixer
    portrules:
      - name: "MAIN L"
        target: "system:playback_1"
      - name: "MAIN R"
        target: "system:playback_2"
  - client: vlc_[0-9]+
    portrules:
      - name: out_1
        target: "jack_mixer:VLC L"
      - name: out_2
        target: "jack_mixer:VLC R"
  - client: "alsa-jack\\.jackP\\.%.*\\/firefox.*%\\.[0-9]+"
    portrules:
      - name: out_000
        target: "jack_mixer:Firefox L"
      - name: out_001
        target: "jack_mixer:Firefox R"
